# Generated by Django 2.1 on 2018-08-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tickets', '0003_auto_20180807_2331'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'ticket')},
        ),
    ]
